### ISSUE TITLE
Improve scikit-api Github page with a good HTML Template

### ISSUE THREAD

**Issue by dilumn** [99xt/scikit-api#38]
Add a good `HTML` template for the scikit-api Github page which is right now hosted in https://99xt.github.io/scikit-api/ 

The existing implementation is in `gh-pages` branch & contribution is welcome from anyone who would like to start contributing to `scikit-api`

**Comment by kushalpandya** [comment]
I can work on this, any particular look and feel that we're aiming for? like particular colors to use in design?

**Comment by dilumn** [comment]
Not much colorful design, but a template which can be readable easily is fine. It should content menu options like in below website,
https://swift.org

Really appreciate if you can find a good template for us. Later we can add relevant content. For now template is enough

**Comment by kushalpandya** [comment]
Hi @dilumn 

So I've been working on site theme with a template. Here's what I've done.

- Find a good, light template. Found one [here](http://zypopwebtemplates.com/free-web-templates/anatine-free-html5-css3-responsive-web-template-499.html). It is licensed under [Creative Commons Attribution license](https://creativecommons.org/licenses/by/2.0/).
    - I've modified default color scheme of it and broke it down to be Jekyll friendly.
- Set up [Jekyll](https://jekyllrb.com/) on `gh-pages` branch as it is GitHub supported and will help us scaling up with content.
- Have a demo site. Check it out [live DEMO here](https://scikit-api-site-yhrtrbygpg.now.sh/)

The changes I've made are not small, I've added lot of files, so before I make PR, please have a look at source in a branch I have available in my fork [available here](https://github.com/kushalpandya/scikit-api/tree/enhanc/gh-pages/SiteTheme) as well as demo, and let me know what you think.

**Comment by dilumn** [comment]
This is excellent work, thank you very much for your help on adding `jekyll` support as well. I couldn't mention it in the issue but you have integrated it. The way you presented here is also great.

Go ahead with your PR to `gh-pages` branch.

Thanks again for your contribution for `scikit-api`
