### ISSUE TITLE
Divide two servers into two docker containers

### ISSUE THREAD

**Issue by dilumn** [99xt/scikit-api#39]
As of now we are successfully starting two servers (Python server on port 5000 & node server on port 8080) when `docker run` executed.

As we go ahead, we can separate these two servers into two docker containers (two docker hub repositories as well).

What are your suggestions on this @tharaka7nw & @samudrak ??

**Comment by tharaka7nw** [comment]
Any particular advantage that we get from separating the service into two servers? Doesn't that make things harder for anyone wants to use our image?

**Comment by dilumn** [comment]
The main disadvantage I also see by separating the servers into two is, users who are going to use this service will have to download two docker images & run both of them.

So shall we go with this one docker container implementation for now & separate them later if we see any advantages?
