### ISSUE TITLE
Create Base Docker library

### ISSUE THREAD

**Issue by samudrak** [99xt/scikit-api#4]

**Comment by priyanshujain** [comment]
what docker library mean here.

**Comment by dilumn** [comment]
Earlier we wanted to create a docker image with all software package we want. So right now we are in the end of this issue

**Comment by priyanshujain** [comment]
So, what is the mean of this open issue?

**Comment by dilumn** [comment]
The base image is right now on docker hub as `99xt/scikit-base`, we need some refactoring for that base image.

**Comment by priyanshujain** [comment]
what I should do for it.
