### ISSUE TITLE
Update Readme file with Github pages URL

### ISSUE THREAD

**Issue by dilumn** [99xt/scikit-api#41]
Github page is up & running for `scikit-api` now on https://99xt.github.io/scikit-api/

Update the Readme on `master` branch with some description about the page.

This Github page will be the official website for `scikit-api`

**Comment by deadpyxel** [comment]
can I get assigned to this?

**Comment by dilumn** [comment]
One pull request is already made on this #43

**Comment by dilumn** [comment]
Fixed #42
